version: '3.8'

volumes:
  prometheus_data: {}


services:
  japp:
    build: ./java-app
    environment:
      - OTEL_EXPORTER_ENDPOINT=http://opentelemetry:4018
      - JAVA_XMX=${JAVA_XMX}
      - JAVA_XMS=${JAVA_XMS}
      - JAVA_GC=${JAVA_GC}
    ports:
     - "4050:4050"


  jaeger:
    image: jaegertracing/all-in-one:1.49.0
    command:
      - '--collector.otlp.grpc.host-port=0.0.0.0:4317'
    ports:
      - 16686:16686
      - 9411:9411

  opentelemetry:
    image: otel/opentelemetry-collector-contrib:0.85.0
    volumes:
      - "./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml"
    ports:
      - 4017:4017
      - 4018:4018
      - 8889:8889


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090

